---
# tasks file for iommu-setup

- name: Install util-linux
  pacman:
    name: util-linux

- name: Install pciutils
  pacman:
    name: pciutils

- name: Install grep
  pacman:
    name: grep

- name: Install python3
  pacman:
    name: python3

- name: Check CPU vendor
  shell: "python3 {{ role_path }}/files/cpu-vendor-parser.py '{{ ansible_processor[1] }}'"
  register: cpu_vendor

- name: Print CPU vendor
  debug:
    msg: "{{ cpu_vendor.stdout }}"

- name: Check for IOMMU support for AMD
  when: cpu_vendor.stdout == "AMD"
  shell: "dmesg | grep 'AMD-Vi'"

- name: Check for IOMMU support for Intel
  when: cpu_vendor.stdout == "INTEL"
  shell: "dmesg | grep 'Virtualization Technology for Directed I/O'"

- name: Look for attached VGA
  shell: "lspci -knn | grep VGA"
  register: lspci_knn_vga

- name: Print lspci output
  debug:
    msg: "{{ lspci_knn_vga.stdout }}"

- name: Parse lscpi output
  shell: "python3 {{ role_path }}/files/lspci-parser.py '{{ lspci_knn_vga.stdout }}'"
  register: vga_main_buses

- name: Print main vga buses
  debug:
    msg: "{{ vga_main_buses.stdout_lines }}"
